import Head from 'next/head'
import { PostCard, Pagination } from '../components'
import { getPosts } from '../services'
import { FeaturedPosts } from '../sections'
import { useContext } from 'react'
import Context from '../contexts/Context'

export default function Home({ posts }) {
  const { currentPage, postsPerPage, searchTerm } = useContext(Context)


  //
  const indexOfLastPost = currentPage * postsPerPage;
  const indexOfFirstPost = indexOfLastPost - postsPerPage;
  const currentPosts = posts.filter(post => {
    if (searchTerm === "") {
      return post
    }
    if (post.node.title.toLowerCase().includes(searchTerm.toLowerCase())) {
      return post
    }
  }).slice(indexOfFirstPost, indexOfLastPost);

  const allPosts = currentPosts.map((post) => (<PostCard post={post.node} key={post.node.title} />))


  return (
    <div className="container mx-auto px-4 md:px-10 mb-8">
      <Head>
        <title>My Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>
      <FeaturedPosts />
      <h1 className='text-center text-4xl font-semibold mb-6'>{searchTerm === '' ? 'Последние Статьи' : 'Найденные статьи'}</h1>
      <div className='grid grid-cols-12 xl:gap-8 md:gap-4 lg:gap-6 gap-3 pb-16'>
        {allPosts.length === 0 ? <p className='text-3xl col-span-12'>Статьи не найдены</p> : allPosts}
      </div>
      <Pagination totalPosts={posts.length} />
    </div>
  )
}

export async function getStaticProps() {

  const posts = (await getPosts() || [])

  return {
    props: { posts }
  }
}

